# env
- name: insert shell proxy(http)
  lineinfile: dest=/etc/profile.d/proxy.sh state=present create=yes mode=0644 regexp="{{ http_proxy }}"
              insertafter=EOF line="export http_proxy={{ http_proxy }}"
  become: yes
  ignore_errors: yes

# git
- name: set git proxy(http)
  shell: "git config --global http.proxy {{ http_proxy }}"
  ignore_errors: yes

- name: set git proxy(https)
  shell: "git config --global https.proxy {{ https_proxy }}"
  ignore_errors: yes

# wget
- name: insert wget proxy(http)
  lineinfile: dest=/etc/wgetrc state=present regexp="{{ http_proxy }}"
              insertafter="^#http_proxy" line="http_proxy={{ http_proxy }}"
  become: yes
  ignore_errors: yes

- name: insert wget proxy(https)
  lineinfile: dest=/etc/wgetrc state=present regexp="{{ https_proxy }}"
              insertafter="^#https_proxy" line="https_proxy={{ https_proxy }}"
  become: yes
  ignore_errors: yes

# curl
- name: insert curl proxy(http)
  lineinfile: dest=/etc/.curlrc state=present create=yes regexp="{{ http_proxy }}"
              insertafter=EOF line="proxy={{ http_proxy }}"
  become: yes
  ignore_errors: yes

# apt
- name: insert apt proxy(http)
  lineinfile: dest=/etc/apt/apt.conf state=present regexp="Acquire::http::Proxy"
              insertafter=EOF line="Acquire::http::Proxy \"{{ http_proxy }}\";" create=yes
  become: yes
  ignore_errors: yes
- name: insert apt proxy(http)
  lineinfile: dest=/etc/apt/apt.conf state=present regexp="Acquire::https::Proxy"
              insertafter=EOF line="Acquire::https::Proxy \"{{ https_proxy }}\";" create=yes
  become: yes
  ignore_errors: yes
