# apt
- name: insert apt proxy(http)
  lineinfile: dest=/etc/apt/apt.conf state=present regexp="Acquire::http::Proxy"
              insertafter=EOF line="Acquire::http::Proxy \"{{ proxy_env.http_proxy }}\";" create=yes
  become: yes
  ignore_errors: yes
- name: insert apt proxy(https)
  lineinfile: dest=/etc/apt/apt.conf state=present regexp="Acquire::https::Proxy"
              insertafter=EOF line="Acquire::https::Proxy \"{{ proxy_env.https_proxy }}\";" create=yes
  become: yes
  ignore_errors: yes

# env
- name: insert shell proxy(http)
  lineinfile: dest=/etc/profile.d/proxy.sh state=present create=yes mode=0644 regexp="export http_proxy"
              insertafter=EOF line="export http_proxy={{ proxy_env.http_proxy }}"
  become: yes
  ignore_errors: yes
- name: insert shell proxy(http)
  lineinfile: dest=/etc/profile.d/proxy.sh state=present create=yes mode=0644 regexp="export https_proxy"
              insertafter=EOF line="export https_proxy={{ proxy_env.https_proxy }}"
  become: yes
  ignore_errors: yes

# git
- name: apt install git
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - git
  become: yes

- name: set git proxy(http)
  git_config:
    name: http.proxy
    scope: global
    value: "{{ proxy_env.http_proxy }}"

- name: set git proxy(https)
  git_config:
    name: https.proxy
    scope: global
    value: "{{ proxy_env.https_proxy }}"

# wget
- name: insert wget proxy(http)
  lineinfile: dest=/etc/wgetrc state=present regexp="http_proxy={{ proxy_env.http_proxy }}"
              insertafter="^#http_proxy.*" line="http_proxy={{ proxy_env.http_proxy }}"
  become: yes
  ignore_errors: yes

- name: insert wget proxy(https)
  lineinfile: dest=/etc/wgetrc state=present regexp="https_proxy={{ proxy_env.https_proxy }}"
              insertafter="^#https_proxy.*" line="https_proxy={{ proxy_env.https_proxy }}"
  become: yes
  ignore_errors: yes

# curl
- name: insert curl proxy(http)
  lineinfile: dest=/etc/.curlrc state=present create=yes regexp="{{ proxy_env.http_proxy }}"
              insertafter=EOF line="proxy={{ proxy_env.http_proxy }}"
  become: yes
  ignore_errors: yes
